In [1]:
# Importing Required Libraries
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np

In [183]:
# Checking the current working directory
os.getcwd()

'E:\\Focus Prism Assessment Project'

In [184]:
# Changing the working directory
os.chdir("E:\Focus Prism Assessment Project")

In [185]:
# Importing Train and Test Datasets
train1=pd.read_csv("Train_Data_X.csv")

In [186]:
train2=pd.read_csv("Train_Data_Y.csv")

In [187]:
test=pd.read_csv("Test_Data_X.csv")

In [188]:
# Dropping the "Unnamed:0" column for convenience
train1=train1.drop("Unnamed: 0",axis=1)

In [189]:
train2=train2.drop("Unnamed: 0",axis=1)

In [190]:
train1.head()

,X_follower_count,X_following_count,X_listed_count,X_mentions_received,X_retweets_received,X_mentions_sent,X_retweets_sent,X_posts,X_network_feature_1,X_network_feature_2,...,Y_following_count,Y_listed_count,Y_mentions_received,Y_retweets_received,Y_mentions_sent,Y_retweets_sent,Y_posts,Y_network_feature_1,Y_network_feature_2,Y_network_feature_3
0,4981,2026,170,57.856207,18.718991,3.523850,1.630532,5.137533,118,65.990909,...,1216,90,0.201007,0.201007,2.118130,0.683873,1.635264,10,20.000000,30.000000
1,45639,902,2661,297.708558,73.997768,55.763536,6.666984,47.722563,561,147.404293,...,442,12158,1675.160105,187.139696,15.242519,5.218120,9.732542,2607,41.289101,1967.639388
2,1259726,377,6129,1817.298643,422.667342,24.043562,15.131286,25.584763,3376,30.048666,...,509,36,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000
3,33719,29367,903,256.829708,47.839261,13.112510,0.679044,24.584411,238,92.779221,...,932,52,2.673828,0.724300,2.118425,0.674264,1.645168,14,20.000000,98.500000
4,1834057,813,30642,3348.533818,776.852854,58.663704,14.616587,35.319419,6271,73.226014,...,2134,207,13.394731,2.851357,8.967214,2.665909,7.547107,39,99.206897,2876.793103

In [191]:
train2.head()

   X_social_than_Y?
0                 0
1                 0
2                 1
3                 1
4                 1

In [192]:
# Converting "train1" and "train2" to dataframes inorder to combine them into a single dataset by the name "train"
df1=pd.DataFrame(train1)

In [193]:
df2=pd.DataFrame(train2)

In [194]:
train=pd.concat([df1,df2],axis=1,sort=False)

In [195]:
train

,X_follower_count,X_following_count,X_listed_count,X_mentions_received,X_retweets_received,X_mentions_sent,X_retweets_sent,X_posts,X_network_feature_1,X_network_feature_2,...,Y_listed_count,Y_mentions_received,Y_retweets_received,Y_mentions_sent,Y_retweets_sent,Y_posts,Y_network_feature_1,Y_network_feature_2,Y_network_feature_3,X_social_than_Y?
0,4981,2026,170,57.856207,18.718991,3.523850,1.630532,5.137533,118,65.990909,...,90,0.201007,0.201007,2.118130,0.683873,1.635264,10,20.000000,30.000000,0
1,45639,902,2661,297.708558,73.997768,55.763536,6.666984,47.722563,561,147.404293,...,12158,1675.160105,187.139696,15.242519,5.218120,9.732542,2607,41.289101,1967.639388,0
2,1259726,377,6129,1817.298643,422.667342,24.043562,15.131286,25.584763,3376,30.048666,...,36,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000,1
3,33719,29367,903,256.829708,47.839261,13.112510,0.679044,24.584411,238,92.779221,...,52,2.673828,0.724300,2.118425,0.674264,1.645168,14,20.000000,98.500000,1
4,1834057,813,30642,3348.533818,776.852854,58.663704,14.616587,35.319419,6271,73.226014,...,207,13.394731,2.851357,8.967214,2.665909,7.547107,39,99.206897,2876.793103,1
5,648,640,31,25.065953,0.201007,6.139168,0.201007,5.529524,40,73.636364,...,7939,350.529553,200.961640,6.216981,3.229434,8.803837,689,67.096916,2404.155653,0
6,298718,591,6229,986.512759,413.321104,8.230425,1.709078,6.150926,2031,95.970098,...,398,28.883328,11.347508,1.750427,0.201007,52.383786,61,38.901961,4036.686275,0
7,154880,10653,2930,277.515485,100.337396,7.115664,0.683873,7.627700,552,146.071823,...,29199,58293.912923,36165.487191,0.201007,0.201007,9.004793,88164,24.061066,679.156485,0
8,263664,799,8825,220.820520,53.114247,3.247668,0.201007,2.237243,464,116.043573,...,63,3.965062,2.721281,0.201007,0.201007,72.803279,16,24.666667,299.500000,1
9,130900,3434,469,185.739302,33.076968,5.096095,0.201007,6.073376,365,122.573003,...,90425,32754.345796,11457.917902,0.724300,0.201007,3.216496,61023,30.574039,1406.618332,0
10,567,308,43,7.920500,0.558183,3.607485,0.719067,3.109838,27,115.647059,...,21,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000,1
11,5201,2235,233,46.008794,27.059005,9.698785,5.176597,8.742395,105,116.587629,...,133,0.679044,0.201007,0.719067,0.201007,1.734569,11,20.000000,30.000000,1
12,7604,1751,201,43.203732,7.163322,13.529314,2.239453,9.126493,95,68.500000,...,3851,291.689819,148.005915,47.098379,0.201007,31.906485,577,296.496516,8068.066202,0
13,138285,820,1435,534.873023,257.415766,64.763102,6.990685,53.216940,862,47.478563,...,72,21.812698,4.718048,7.950354,2.248836,5.271894,42,86.911765,1149.441176,1
14,648,640,31,25.065953,0.201007,6.139168,0.201007,5.529524,40,73.636364,...,5207,910.361230,587.679117,60.376109,0.201007,42.126393,1803,179.005962,5786.679133,0
15,117963,1339,9970,379.510460,134.620446,22.589661,5.134538,21.867532,801,205.542033,...,133,0.679044,0.201007,0.719067,0.201007,1.734569,11,20.000000,30.000000,0
16,71647,44302,1457,20.807127,6.730709,1.182411,0.201007,10.149135,57,92.106383,...,123,34.296870,5.435064,11.757928,1.221638,7.167191,71,99.403226,5951.354839,1
17,808,734,23,6.114410,0.558183,2.709399,1.698974,3.192265,20,159.500000,...,70,2.198847,0.201007,1.226766,0.201007,1.221638,14,28.250000,812.750000,1
18,20246,453,947,238.133510,59.348589,68.362386,10.571859,30.666503,414,226.073892,...,28,0.719067,0.201007,1.216509,0.201007,0.708758,11,302.000000,8839.000000,1
19,131970,404,6994,1303.530268,340.306289,9.603840,0.683873,14.108088,2345,79.589006,...,26,0.201007,0.201007,0.201007,0.201007,1.216560,10,20.000000,30.000000,1
20,78781,6252,1991,194.791684,114.359536,27.687288,3.577272,25.321511,388,79.916667,...,3186,978.212757,151.537755,0.201007,0.201007,0.201007,774,329.220493,20386.015564,1
21,23280,535,846,236.104864,113.336585,12.746411,1.681439,19.654010,476,125.210638,...,6229,986.512759,413.321104,8.230425,1.709078,6.150926,2031,95.970098,3895.446569,0
22,2256641,775,22690,977.928665,422.851579,1.731422,0.729586,1.695513,1927,61.487830,...,16348,693.094997,171.594261,13.625948,2.675830,15.149373,1333,288.132983,9337.214876,1
23,775,685,64,8.216597,1.419386,3.137819,1.669413,3.665330,25,148.800000,...,11966,13564.810676,5889.048490,25.911447,5.583722,132.412417,21688,26.859364,1143.202016,0
24,1259726,377,6129,1817.298643,422.667342,24.043562,15.131286,25.584763,3376,30.048666,...,1081,129.283764,42.984262,44.500575,1.166739,55.025675,281,204.297794,7275.231618,1
25,721,255,37,0.708758,0.201007,0.201007,0.201007,0.201007,11,21.000000,...,497,60.262442,3.299955,10.624789,0.201007,9.638286,121,244.225225,7557.405405,0
26,1253,729,87,1.162008,1.162008,3.285573,0.201007,4.306307,12,20.500000,...,82,1.915379,0.201007,2.094035,0.674264,0.674264,14,174.750000,1735.000000,1
27,5735,982,497,60.262442,3.299955,10.624789,0.201007,9.638286,121,244.225225,...,2930,277.515485,100.337396,7.115664,0.683873,7.627700,552,146.071823,6332.397790,0
28,2260711,273,12700,27161.258875,3766.180031,54.365603,26.196767,36.699444,35655,36.870017,...,72,24.711592,14.288534,4.271535,1.198764,9.332730,60,137.098039,6105.882353,1
29,15052,1985,690,197.014834,41.915418,51.292828,1.679018,46.702925,360,103.403955,...,35,3.322327,0.201007,0.708758,0.708758,10.125633,14,26.000000,6561.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2681,130928,5449,398,28.883328,11.347508,1.750427,0.201007,52.383786,61,38.901961,...,2533,30.420216,8.629318,0.201007,0.201007,0.201007,79,341.188406,17484.115942,0
2682,9143,712,477,22.244042,5.627046,30.331870,5.077334,14.033519,46,143.138889,...,9970,379.510460,134.620446,22.589661,5.134538,21.867532,801,205.542033,5565.939774,0
2683,15052,1985,690,197.014834,41.915418,51.292828,1.679018,46.702925,360,103.403955,...,53,2.302726,0.201007,1.147521,0.201007,1.138103,12,30.000000,632.500000,1
2684,632008,714,7542,1229.937490,658.660182,8.104558,2.681132,24.610071,2546,55.838659,...,36,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000,1
2685,615,653,54,23.554413,2.100972,11.289124,3.733011,11.730890,44,96.500000,...,19735,347272.477900,104699.348415,22.817679,3.305800,26.970532,213728,25.348203,1260.512781,0
2686,4321532,299,32761,14137.188162,7546.497518,4.203988,0.679044,20.433063,25323,31.303281,...,10893,535.407665,188.776136,21.972573,2.720409,22.336809,1073,249.764160,6758.430826,1
2687,25245,1483,35,3.322327,0.201007,0.708758,0.708758,10.125633,14,26.000000,...,11966,13564.810676,5889.048490,25.911447,5.583722,132.412417,21688,26.859364,1143.202016,0
2688,480462,11988,16314,3591.051093,1371.150088,9.069975,2.636280,31.651831,6877,80.814662,...,3700,331.188967,178.286313,10.372534,4.833663,14.358728,692,102.986957,3807.766667,0
2689,1344,471,64,1.110408,0.201007,0.201007,0.201007,1.191924,12,856.000000,...,22252,353.067432,84.660443,13.698454,2.690147,8.719731,706,254.338068,7198.464489,0
2690,889350,223,5666,6474.627746,3928.580374,36.234563,1.705204,180.291683,10963,30.028592,...,20,0.201007,0.201007,0.201007,0.201007,0.703680,10,20.000000,30.000000,1
2691,173922,2844,16348,693.094997,171.594261,13.625948,2.675830,15.149373,1333,288.132983,...,3374,517.047848,248.943081,14.942679,1.191924,21.998267,983,61.016211,3072.892604,1
2692,747,54,57,41.238295,24.737691,15.566306,7.396391,22.756577,64,67.218182,...,1801,1024.888986,287.786528,9.179513,3.689863,10.221701,1753,50.759207,1281.028329,0
2693,10743,975,32,1.268844,0.734925,0.734925,0.201007,0.734925,12,70.500000,...,5459,2086.471907,1116.427312,41.287287,2.742416,44.462772,3058,79.964378,1584.076101,0
2694,19612,17677,298,1145.749711,780.587362,55.104081,14.335113,64.203812,1772,43.469296,...,233,46.008794,27.059005,9.698785,5.176597,8.742395,105,116.587629,2262.690722,1
2695,454564,1519,5207,910.361230,587.679117,60.376109,0.201007,42.126393,1803,179.005962,...,2661,297.708558,73.997768,55.763536,6.666984,47.722563,561,147.404293,2863.847943,0
2696,494,195,34,0.201007,0.201007,0.698654,0.201007,0.698654,10,20.000000,...,2930,277.515485,100.337396,7.115664,0.683873,7.627700,552,146.071823,6332.397790,0
2697,110,186,20,0.713887,0.201007,0.679044,0.201007,2.238459,11,192.000000,...,25,3.133476,0.693677,3.148798,0.674264,2.104616,16,48.500000,584.500000,0
2698,1352398,371,15667,38259.697324,29105.467983,4.130836,1.161911,32.563005,52590,23.092448,...,3157,96.097404,50.185889,0.201007,0.201007,0.201007,213,50.093137,3247.367647,1
2699,65314,996,2692,453.527100,144.290811,7.563329,4.095874,6.127438,897,88.708193,...,10893,535.407665,188.776136,21.972573,2.720409,22.336809,1073,249.764160,6758.430826,0
2700,2520,397,139,2.252948,0.646569,0.674264,0.674264,1.192324,15,80.600000,...,8762,1748.425746,695.261335,8.996941,0.201007,69.955955,2777,125.734781,5306.962620,0
2701,366510,506,3401,2335.793859,830.527828,99.837266,16.123113,165.070353,3460,37.914359,...,5666,6474.627746,3928.580374,36.234563,1.705204,180.291683,10963,30.028592,1210.805341,0
2702,823531,2707,13272,175.215311,57.346452,13.309892,5.231588,10.097496,361,78.414085,...,49,4.584929,0.624732,10.270716,4.064917,8.846312,21,212.363636,3885.727273,1
2703,2520,397,139,2.252948,0.646569,0.674264,0.674264,1.192324,15,80.600000,...,90425,32754.345796,11457.917902,0.724300,0.201007,3.216496,61023,30.574039,1406.618332,0
2704,48827,898,1256,494.477491,148.206984,6.063391,3.633492,42.351392,1007,52.902778,...,57,41.238295,24.737691,15.566306,7.396391,22.756577,64,67.218182,820.636364,1
2705,236173,898,2814,154.387147,47.942153,25.083203,5.101450,25.214145,317,179.200647,...,497,60.262442,3.299955,10.624789,0.201007,9.638286,121,244.225225,7557.405405,1
2706,221051,946,8633,7866.476015,3148.772901,0.679044,0.201007,25.474660,10570,62.962078,...,3186,978.212757,151.537755,0.201007,0.201007,0.201007,774,329.220493,20386.015564,1
2707,49376,42299,1466,0.904680,0.551075,0.201007,0.201007,0.201007,12,63.000000,...,151,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000,1
2708,242579,7601,3722,485.267271,213.352778,14.396661,4.081022,20.147843,904,83.098999,...,1630,80.990041,17.887214,6.455354,1.128685,2.140641,173,152.030675,2961.515337,1
2709,1607591,133,9896,779.066239,435.256884,0.719067,0.201007,1.699580,1716,29.979033,...,2824,49.647821,8.936252,4.288813,1.211533,3.254078,102,278.255319,8163.000000,1
2710,7360389,135,43610,24946.300128,19194.002146,10.647895,2.707247,16.532477,46916,27.320320,...,420,14.392779,5.271446,3.544578,0.683873,1.650386,38,106.321429,1734.928571,1

In [196]:
train.columns

Index(['X_follower_count', 'X_following_count', 'X_listed_count',
       'X_mentions_received', 'X_retweets_received', 'X_mentions_sent',
       'X_retweets_sent', 'X_posts', 'X_network_feature_1',
       'X_network_feature_2', 'X_network_feature_3', 'Y_follower_count',
       'Y_following_count', 'Y_listed_count', 'Y_mentions_received',
       'Y_retweets_received', 'Y_mentions_sent', 'Y_retweets_sent', 'Y_posts',
       'Y_network_feature_1', 'Y_network_feature_2', 'Y_network_feature_3',
       'X_social_than_Y?'],
      dtype='object')

In [197]:
predictor_vars=['X_follower_count', 'X_following_count', 'X_listed_count',
       'X_mentions_received', 'X_retweets_received', 'X_mentions_sent',
       'X_retweets_sent', 'X_posts', 'X_network_feature_1',
       'X_network_feature_2', 'X_network_feature_3', 'Y_follower_count',
       'Y_following_count', 'Y_listed_count', 'Y_mentions_received',
       'Y_retweets_received', 'Y_mentions_sent', 'Y_retweets_sent', 'Y_posts',
       'Y_network_feature_1', 'Y_network_feature_2', 'Y_network_feature_3']

In [198]:
x,y=train[predictor_vars],train[['X_social_than_Y?']]

In [199]:
x.head()

,X_follower_count,X_following_count,X_listed_count,X_mentions_received,X_retweets_received,X_mentions_sent,X_retweets_sent,X_posts,X_network_feature_1,X_network_feature_2,...,Y_following_count,Y_listed_count,Y_mentions_received,Y_retweets_received,Y_mentions_sent,Y_retweets_sent,Y_posts,Y_network_feature_1,Y_network_feature_2,Y_network_feature_3
0,4981,2026,170,57.856207,18.718991,3.523850,1.630532,5.137533,118,65.990909,...,1216,90,0.201007,0.201007,2.118130,0.683873,1.635264,10,20.000000,30.000000
1,45639,902,2661,297.708558,73.997768,55.763536,6.666984,47.722563,561,147.404293,...,442,12158,1675.160105,187.139696,15.242519,5.218120,9.732542,2607,41.289101,1967.639388
2,1259726,377,6129,1817.298643,422.667342,24.043562,15.131286,25.584763,3376,30.048666,...,509,36,0.201007,0.201007,0.201007,0.201007,0.201007,10,20.000000,30.000000
3,33719,29367,903,256.829708,47.839261,13.112510,0.679044,24.584411,238,92.779221,...,932,52,2.673828,0.724300,2.118425,0.674264,1.645168,14,20.000000,98.500000
4,1834057,813,30642,3348.533818,776.852854,58.663704,14.616587,35.319419,6271,73.226014,...,2134,207,13.394731,2.851357,8.967214,2.665909,7.547107,39,99.206897,2876.793103

In [200]:
y.head()

   X_social_than_Y?
0                 0
1                 0
2                 1
3                 1
4                 1

In [201]:
# Splitting the datasets for efficient implementation of ML Algorithm
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [202]:
# the test and train datasets from the 'train' dataset are in the ratio 25:75
len(X_train)

2033

In [203]:
len(X_test)

678

In [204]:
# Implementing Logistic Regression model
from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

logReg.fit(X_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [205]:
logReg_y_pred = logReg.predict(X_test)

In [206]:
# From the output of this confusion matrix we can see that the Logistic Regression model predicted 265-TN ,86-FP, 93-FN and 234-TP 
# In this case P means A is more influential than B, N means B is more influential than A
# So, we can say that this algorithm predicted more True values than False values

from sklearn.metrics import confusion_matrix,accuracy_score, auc, f1_score
logReg_CM = confusion_matrix(y_test, logReg_y_pred)
logReg_CM

array([[265,  86],
       [ 93, 234]], dtype=int64)

In [207]:
logReg_accuracy = accuracy_score(y_test,logReg_y_pred)
logReg_accuracy

0.7359882005899705

In [208]:
# f1 score was calculated inspite of calculating Accuracy score 
# Because Accuracy is the most intuitive performance measure and it is simply a ratio of correctly predicted observation to the total observations.
# F1 Score is the weighted average of Precision and Recall
# The f1 score obtained was 0.72

logReg_f1 = f1_score(y_test,logReg_y_pred)
logReg_f1

0.723338485316847

In [209]:
# For fine tuning the prediction accuracy, Random Forest Classification Model was implemented

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [210]:
rfc.fit(x,y)
rfc_y_pred = rfc.predict(X_test)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

In [211]:
accuracy_score(y_test,rfc_y_pred)

0.9926253687315634

In [212]:
rfc_f1 = f1_score(y_test,rfc_y_pred)
rfc_f1

0.9922958397534669

In [213]:
# The obtained values of Accuracy score and f1 score were high enough to implement this Algorithm 
rfc_y_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1], dtype=int64)

In [214]:
# It can be seen that the predicted values are almost similar to the true values

y_test

      X_social_than_Y?
1809                 1
1919                 0
891                  0
2054                 1
565                  1
1881                 0
615                  0
2057                 1
124                  0
1414                 0
179                  1
581                  1
2487                 1
722                  1
70                   0
996                  1
289                  1
1969                 0
619                  1
1712                 0
1287                 0
1096                 0
578                  1
1002                 0
1691                 1
923                  1
227                  0
333                  0
982                  0
692                  0
...                ...
2066                 1
757                  1
2519                 0
1572                 1
149                  1
107                  0
1426                 1
2099                 1
1                    0
384                  0
530                  1
588                  1
2016                 0
453                  1
1519                 0
1615                 0
1957                 1
731                  1
1275                 1
1246                 0
1323                 0
2210                 0
2063                 1
2295                 1
2092                 0
1830                 0
52                   1
2288                 0
1428                 0
20                   1

[678 rows x 1 columns]

In [215]:
# The Random Forest Classification ML Algorithm was implemented on the 'test' dataset

predictions=rfc.predict(test[predictor_vars])

In [216]:
predictions

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [217]:
predictions=pd.DataFrame({'Predicted': predictions})

In [218]:
predictions

      Predicted
0             0
1             0
2             1
3             0
4             0
5             0
6             1
7             1
8             0
9             0
10            0
11            0
12            0
13            1
14            0
15            1
16            1
17            1
18            0
19            1
20            0
21            0
22            1
23            1
24            0
25            0
26            0
27            1
28            1
29            1
...         ...
1133          0
1134          0
1135          1
1136          1
1137          1
1138          0
1139          1
1140          0
1141          0
1142          1
1143          1
1144          1
1145          1
1146          1
1147          0
1148          1
1149          0
1150          0
1151          1
1152          0
1153          0
1154          0
1155          1
1156          0
1157          1
1158          1
1159          1
1160          0
1161          0
1162          0

[1163 rows x 1 columns]

In [219]:
predictions.to_csv("Test_Predictions.csv", sep=',', encoding='utf-8')

In [220]:
TEST=pd.read_csv("Test_Predictions.csv")

In [221]:
TEST.head()

   Unnamed: 0  Predicted
0           0          0
1           1          0
2           2          1
3           3          0
4           4          0

In [222]:
#  It can be seen that the total of predicted values of '0' is more than that of '1'
#  Therefore, B is more influential than A

TEST["Predicted"].value_counts()

0    601
1    562
Name: Predicted, dtype: int64